/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.TabModel;
import Model.WorkerModel;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sistema30
 */
public class Main extends javax.swing.JFrame {
    private final Object[] header={"ID", "Nombres", "Apellidos", "N° INSS", "Salario Base", "IR", "INSS", "Salario neto"};
    private final Object[] wheader={"ID", "Cedula", "INSS", "Nombres", "Apellidos", "Dirección", "Titulo", "Salario Base"};
    private DefaultTableModel tabmod;
    private DefaultTableModel wtabmod;
    private TabModel tmod;
    private WorkerModel mod;
    /**
     * Creates new form Main
     */
    public Main() {
        tmod=new TabModel();
        mod=new WorkerModel();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainpane = new javax.swing.JScrollPane();
        Tab = new javax.swing.JTable();
        workerTab = new javax.swing.JScrollPane();
        WTab = new javax.swing.JTable();
        TabPane = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        Planilla = new javax.swing.JMenu();
        addmnitem = new javax.swing.JMenuItem();
        Opciones = new javax.swing.JMenu();

        Tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        mainpane.setViewportView(Tab);

        WTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        workerTab.setViewportView(WTab);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().add(TabPane, java.awt.BorderLayout.CENTER);

        Planilla.setText("Planilla");

        addmnitem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        addmnitem.setText("Agregar");
        addmnitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addmnitemActionPerformed(evt);
            }
        });
        Planilla.add(addmnitem);

        jMenuBar1.add(Planilla);

        Opciones.setText("Opciones");
        jMenuBar1.add(Opciones);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addmnitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addmnitemActionPerformed
        AddDlg dl=new AddDlg(this, true);
        dl.setMod(mod);
        dl.setVisible(true);
        fireTables();
    }//GEN-LAST:event_addmnitemActionPerformed
    private void fireTables(){
        Object[][] listed=tmod.toMatrix(mod.getWorkers());
        wtabmod=new DefaultTableModel(listed, wheader);
        WTab.setModel(wtabmod);
        Object[][] plan=tmod.plan(mod.getWorkers(), header);
        tabmod=new DefaultTableModel(plan, header);
        Tab.setModel(tabmod);
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        TabPane.addTab("Trabajadores", null, workerTab, "This is");
        TabPane.addTab("Planilla", null, mainpane, ":v");
        tabmod=new DefaultTableModel(new Object[0][0], header);
        wtabmod=new DefaultTableModel(new Object[0][0], wheader);
        Tab.setModel(tabmod);
        WTab.setModel(wtabmod);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Opciones;
    private javax.swing.JMenu Planilla;
    private javax.swing.JTable Tab;
    private javax.swing.JTabbedPane TabPane;
    private javax.swing.JTable WTab;
    private javax.swing.JMenuItem addmnitem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane mainpane;
    private javax.swing.JScrollPane workerTab;
    // End of variables declaration//GEN-END:variables
}
